version: '3.9'

volumes:
  elastic_data:
    name: elastic_data
    external: false

networks: 
  elasticapp_net:
    name: elasticapp_net
    external: false

services:

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g" 
      ELASTIC_PASSWORD: V2yvGtc2hNmydgNY
      cluster.name: es-cluster
      bootstrap.memory_lock: "true"

    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      elasticapp_net:

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: logstash
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "50000:50000"
    environment:
      LS_JAVA_OPTS: "-Xms1g -Xmx1g"
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      elasticapp_net:

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    container_name: kibana
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    environment:
      KIBANA_SYSTEM_PASSWORD: V2yvKib
    depends_on:
      - elasticsearch
    networks:
      elasticapp_net:


